name: Java application

on:
  push:
    branches: [ "CIforJava" ]
  pull_request:
    branches: [ "CIforJava" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Compile and run Java program
      run: |
        javac ExampleJavaApp.java
        java ExampleJavaApp

    # Save the generated 'output.png' file as an artifact
    - name: Save PNG artifact
      uses: actions/upload-artifact@v2
      with:
        name: png-artifacts
        path: output.png
