name: Python application

on:
  pull_request:
    branches: [ "main" ]  # Adjust this to match your branch name

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run datafold_script.py
      run: |
        python datafold_script.py
    - name: Test with pytest
      run: |
        echo "testing"
    - name: Create distribution packages
      run: |
    - name: Create distribution packages
      run: |
       python -m pip install --upgrade pip
       pip install setuptools wheel
       python setup.py sdist bdist_wheel

    # Save binaries as an artifact
    - name: Save dist artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-artifacts
        path: dist

    # Save the PNG file as an artifact (for testing)
    - name: Save PNG artifact
      uses: actions/upload-artifact@v2
      with:
        name: png-artifacts
        path: test_plot.png
